version: '3.4'

services:
  ms-sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
  hmm.serviceapi:
    image: ${DOCKER_REGISTRY-}hmmserviceapi
    build:
      context: .
      dockerfile: src/Hmm.ServiceApi/Dockerfile
