services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: hmm-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Shcdlhgm1!"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    networks:
      - hmm-network
    volumes:
      - G:/Projects2/Hmm/data/sqlserver:/var/opt/mssql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  hmm-seq:
    image: datalust/seq:latest
    container_name: hmm-seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80
    networks:
      - hmm-network

networks:
  hmm-network:
    driver: bridge
