/***** Postgres version of database script *****/
DROP TABLE IF EXISTS authors CASCADE;
DROP TABLE IF EXISTS contacts CASCADE;
DROP TABLE IF EXISTS notecatalogs CASCADE;
DROP TABLE IF EXISTS notes CASCADE;
DROP TABLE IF EXISTS notetagrefs CASCADE;
DROP TABLE IF EXISTS tags CASCADE;
DROP TYPE if exists note_content_format_type CASCADE;
/****** Object:  Table Authors    Script Date: 2024/06/24 16:05:01 ******/
CREATE TABLE Contacts(
    Id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Contact VARCHAR NULL,
	IsActivated BOOLEAN NOT NULL default true,
	Description VARCHAR(1000) NULL
);

CREATE TABLE Authors(
    Id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    AccountName VARCHAR(256) NOT NULL,
    Role INT NOT NULL, -- Adjust based on how you store enums
    ContactInfo INT NULL,
	IsActivated BOOLEAN NOT NULL,
	Description VARCHAR(1000) NULL,
    FOREIGN KEY(ContactInfo) REFERENCES Contacts(Id) ON DELETE NO ACTION
);
/****** Object:  Index IDX_UniqueAccountName    Script Date: 2024/06/24 3:15:56 PM ******/
CREATE UNIQUE INDEX idx_authors_accountname ON Authors (AccountName ASC);

/****** Object:  Table Tags    Script Date: 03/05/2024 16:05:01 ******/
CREATE TABLE Tags(
    Id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	Name VARCHAR(200) NOT NULL,
	IsActivated BOOLEAN NOT NULL,
	Description VARCHAR(1000) NULL
);
CREATE UNIQUE INDEX idx_TagName ON Tags(Name);

/****** Object:  Type NoteContentFormat    Script Date: 2024/06/24 16:05:01 ******/
CREATE TYPE Note_Content_Format_Type AS ENUM ('plain_text', 'xml', 'json', 'markdown');

/****** Object:  Table NoteCatalogs    Script Date: 06/05/2024 16:05:01 ******/
CREATE TABLE NoteCatalogs(
    Id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	Name VARCHAR(200) NOT NULL,
	Schema xml NOT NULL,
	Format Note_Content_Format_Type,
	IsDefault BOOLEAN NOT NULL default false,
	Description VARCHAR(1000) NULL
);
/****** Object:  Index idx_UniqueCatalogName    Script Date: 2024/06/24 1:55:07 PM ******/
CREATE UNIQUE INDEX idx_UniqueCatalogName ON NoteCatalogs(Name);

/****** Object:  Table Notes Script Date: 2024/06/24 16:05:01 ******/
CREATE TABLE Notes(
    Id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	Subject VARCHAR(1000) NOT NULL,
	Content VARCHAR NOT NULL,
	CatalogId INT NOT NULL,
	AuthorId INT NOT NULL,
	IsDeleted BOOLEAN NOT NULL DEFAULT FALSE,
	CreateDate TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	LastModifiedDate TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	Description VARCHAR(1000) NULL,
	Ts bytea DEFAULT gen_random_bytes(8),
    FOREIGN KEY(CatalogId) REFERENCES NoteCatalogs(Id) ON DELETE NO ACTION,
    FOREIGN KEY(AuthorId) REFERENCES Authors(Id) ON DELETE NO ACTION
);

CREATE OR REPLACE FUNCTION update_ts_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.ts = gen_random_bytes(8);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_ts_trigger
BEFORE UPDATE ON notes
FOR EACH ROW
    EXECUTE FUNCTION update_ts_column();

/****** Object:  Table NoteTagRefs    Script Date: 2024/06/24 16:05:01 ******/
CREATE TABLE NoteTagRefs(
    Id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	NoteId INT NOT NULL,
	TagId INT NOT NULL,
    FOREIGN KEY(NoteId) REFERENCES Notes(Id) ON DELETE CASCADE,
    FOREIGN KEY(TagId) REFERENCES Tags(Id) ON DELETE CASCADE 
);

CREATE UNIQUE INDEX idx_unique_noteid_tagid ON NoteTagRefs (NoteId, TagId);
