// <auto-generated />
using System;
using Hmm.Core.Dal.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hmm.Core.Dal.EF.Migrations
{
    [DbContext(typeof(HmmDataContext))]
    [Migration("20260426042459_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "note_content_format_type", "note_content_format_type", new[] { "plain_text", "xml", "json", "markdown" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hmm.Core.Map.DbEntity.AuthorDao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("accountname");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("avatarurl");

                    b.Property<string>("Bio")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("bio");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActivated")
                        .HasColumnType("boolean")
                        .HasColumnName("isactivated");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<string>("TimeZone")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("timezone");

                    b.Property<int?>("contactinfo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AccountName")
                        .IsUnique()
                        .HasDatabaseName("uq_authors_accountname");

                    b.HasIndex("contactinfo");

                    b.ToTable("authors", (string)null);
                });

            modelBuilder.Entity("Hmm.Core.Map.DbEntity.ContactDao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contact");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActivated")
                        .HasColumnType("boolean")
                        .HasColumnName("isactivated");

                    b.HasKey("Id");

                    b.ToTable("contacts", (string)null);
                });

            modelBuilder.Entity("Hmm.Core.Map.DbEntity.HmmNoteDao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdate");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("createdby");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("lastmodifiedby");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastmodifieddate");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("subject");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasColumnName("ts");

                    b.Property<int>("authorid")
                        .HasColumnType("integer");

                    b.Property<int>("catalogid")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("authorid")
                        .HasDatabaseName("ix_notes_authorid");

                    b.HasIndex("catalogid")
                        .HasDatabaseName("ix_notes_catalogid");

                    b.ToTable("notes", (string)null);
                });

            modelBuilder.Entity("Hmm.Core.Map.DbEntity.NoteCatalogDao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<int>("FormatType")
                        .HasColumnType("integer")
                        .HasColumnName("format");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("isdefault");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Schema")
                        .IsRequired()
                        .HasColumnType("xml")
                        .HasColumnName("schema");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_notecatalogs_name");

                    b.ToTable("notecatalogs", (string)null);
                });

            modelBuilder.Entity("Hmm.Core.Map.DbEntity.NoteTagRefDao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("NoteId")
                        .HasColumnType("integer")
                        .HasColumnName("noteid");

                    b.Property<int>("TagId")
                        .HasColumnType("integer")
                        .HasColumnName("tagid");

                    b.HasKey("Id");

                    b.HasIndex("NoteId")
                        .HasDatabaseName("ix_notetagrefs_noteid");

                    b.HasIndex("TagId")
                        .HasDatabaseName("ix_notetagrefs_tagid");

                    b.ToTable("notetagrefs", (string)null);
                });

            modelBuilder.Entity("Hmm.Core.Map.DbEntity.TagDao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActivated")
                        .HasColumnType("boolean")
                        .HasColumnName("isactivated");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_tags_name");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("Hmm.Core.Map.DbEntity.AuthorDao", b =>
                {
                    b.HasOne("Hmm.Core.Map.DbEntity.ContactDao", "ContactInfo")
                        .WithMany()
                        .HasForeignKey("contactinfo");

                    b.Navigation("ContactInfo");
                });

            modelBuilder.Entity("Hmm.Core.Map.DbEntity.HmmNoteDao", b =>
                {
                    b.HasOne("Hmm.Core.Map.DbEntity.AuthorDao", "Author")
                        .WithMany()
                        .HasForeignKey("authorid")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_notes_authors");

                    b.HasOne("Hmm.Core.Map.DbEntity.NoteCatalogDao", "Catalog")
                        .WithMany()
                        .HasForeignKey("catalogid")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_notes_catalogs");

                    b.Navigation("Author");

                    b.Navigation("Catalog");
                });

            modelBuilder.Entity("Hmm.Core.Map.DbEntity.NoteTagRefDao", b =>
                {
                    b.HasOne("Hmm.Core.Map.DbEntity.HmmNoteDao", "Note")
                        .WithMany("Tags")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notetagrefs_notes");

                    b.HasOne("Hmm.Core.Map.DbEntity.TagDao", "Tag")
                        .WithMany("Notes")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notetagrefs_tags");

                    b.Navigation("Note");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Hmm.Core.Map.DbEntity.HmmNoteDao", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Hmm.Core.Map.DbEntity.TagDao", b =>
                {
                    b.Navigation("Notes");
                });
#pragma warning restore 612, 618
        }
    }
}
